"""Interact with Huawei inverters over Modbus."""

from .connection import (
    HuaweiModbusConnection,
    HuaweiUnit,
    SupportsHuaweiPdu,
    create_rtu_connection,
    create_scan_rtu_connection,
    create_scan_tcp_connection,
    create_tcp_connection,
)
from .device import (
    EMMADevice,
    HuaweiSolarDevice,
    HuaweiSolarDeviceWithLogin,
    MeterDevice,
    SChargerDevice,
    SDongleDevice,
    SmartLoggerDevice,
    SUN2000Device,
    UpdateReport,
    create_device_instance,
    create_sub_device_instance,
)
from .device_discovery import DeviceIdentifier, DeviceInfo, get_device_identifiers, get_device_infos
from .exceptions import (
    ConnectionException,
    ConnectionInterruptedException,
    DecodeError,
    EncodeError,
    HuaweiSolarException,
    InvalidCredentials,
    PeakPeriodsValidationError,
    PermissionDeniedError,
    ReadException,
    TimeOfUsePeriodsException,
    WriteException,
)
from .files import (
    OptimizerHistoryRealTimeDataUnit,
    OptimizerOnlineStatus,
    OptimizerRealTimeData,
    OptimizerRunningStatus,
    OptimizerSystemInformation,
)
from .periods import (
    ChargeDischargePeriod,
    ChargeFlag,
    HUAWEI_LUNA2000_TimeOfUsePeriod,
    LG_RESU_TimeOfUsePeriod,
    PeakSettingPeriod,
)
from .register_names import RegisterName
from .registry import REGISTER_LOCATIONS, SETTING_REGISTERS, RegisterLocation

__all__ = [
    "REGISTER_LOCATIONS",
    "SETTING_REGISTERS",
    "ChargeDischargePeriod",
    "ChargeFlag",
    "ConnectionException",
    "ConnectionInterruptedException",
    "DecodeError",
    "DeviceIdentifier",
    "DeviceInfo",
    "EMMADevice",
    "EncodeError",
    "HUAWEI_LUNA2000_TimeOfUsePeriod",
    "HuaweiModbusConnection",
    "HuaweiSolarDevice",
    "HuaweiSolarDeviceWithLogin",
    "HuaweiSolarException",
    "HuaweiUnit",
    "InvalidCredentials",
    "LG_RESU_TimeOfUsePeriod",
    "MeterDevice",
    "OptimizerHistoryRealTimeDataUnit",
    "OptimizerOnlineStatus",
    "OptimizerRealTimeData",
    "OptimizerRunningStatus",
    "OptimizerSystemInformation",
    "PeakPeriodsValidationError",
    "PeakSettingPeriod",
    "PermissionDeniedError",
    "ReadException",
    "RegisterLocation",
    "RegisterName",
    "SChargerDevice",
    "SDongleDevice",
    "SUN2000Device",
    "SmartLoggerDevice",
    "SupportsHuaweiPdu",
    "TimeOfUsePeriodsException",
    "UpdateReport",
    "WriteException",
    "create_device_instance",
    "create_rtu_connection",
    "create_scan_rtu_connection",
    "create_scan_tcp_connection",
    "create_sub_device_instance",
    "create_tcp_connection",
    "get_device_identifiers",
    "get_device_infos",
]
